bahari_web/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("bahari_web.website.urls", namespace="website")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bahari_web/website/urls.py
from django.urls import path

from .views import index, menu

app_name = "website"

urlpatterns = [
    path("", index, name="index"),
    path("menu", menu, name="menu"),
]

bahari_web/apps/events/models.py
from django.db import models


class Event(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    photo = models.ImageField(upload_to="events/photos/", blank=True, null=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Event"
        verbose_name_plural = "Events"
        ordering = ["-start_date"]

    def __str__(self):
        return self.name

bahari_web/apps/live_musics/models.py
from django.db import models


class LiveMusic(models.Model):
    name = models.CharField(max_length=255)
    schedule = models.CharField(max_length=255)
    description = models.TextField()
    photo = models.ImageField(upload_to="live_music/photos/", blank=True, null=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Live Music"
        verbose_name_plural = "Live Music"
        ordering = ["name"]

    def __str__(self):
        return self.name

bahari_web/apps/users/models.py
from typing import Any

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.db import models


class CustomUserManager(UserManager):
    def create_user(self, email: str, password: str, **extra_fields: Any) -> "User":  # type: ignore
        """
        Creates and saves a User with the given email.
        """

        user: User = self.model(
            email=email,
            is_superuser=False,
            is_staff=False,
            is_blocked=False,
            is_active=True,  # type: ignore
            **extra_fields,
        )

        if password:
            user.set_password(password)

        user.save(using=self._db)

        return user

    def create_superuser(self, email, password, **extra_fields) -> "User":  # type: ignore
        user = self.create_user(email=email, password=password, **extra_fields)
        user.is_staff = True
        user.is_active = True
        user.is_blocked = False
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    name = models.CharField(max_length=255, blank=True)
    email = models.EmailField("Email Address", unique=True, blank=True, null=True)
    phone = models.CharField(max_length=30, unique=True, null=True, blank=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField("Staff Status", default=False)
    is_blocked = models.BooleanField(default=False)

    objects = CustomUserManager()
    USERNAME_FIELD = "email"

    def __str__(self) -> str:
        return self.name or self.email or f"#{self.id}"

bahari_web/website/views.py
from django.http import HttpRequest, HttpResponse

from django.shortcuts import render

from bahari_web.apps.events.models import Event
from bahari_web.apps.live_musics.models import LiveMusic


def index(request: HttpRequest) -> HttpResponse:
    events = Event.objects.filter(is_active=True).order_by('-start_date')[:3]
    live_musics = LiveMusic.objects.filter(is_active=True)

    context = {
        "title": "Bahari Irish Pub",
        "current_tab": "home",
        "events": events,
        "live_musics": live_musics,
    }
    return render(request, "index.html", context)


def menu(request: HttpRequest) -> HttpResponse:
    context = {
        "title": "Menu - Bahari Irish Pub",
        "current_tab": "menu",
    }

    return render(request, "menu.html", context)

templates/base.html
{% load compress static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/png" href="{% static 'imgs/bahari-logo.ico' %}"/>
    <title>{{ title }}</title>

    {% compress css %}
        <link rel="stylesheet" href="{% static 'css/fonts.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    {% endcompress %}
</head>
<body>
    {% block header %}
    <header class="header">
        <div class="header__container container">
            <a href="{% url 'website:index' %}" class="header__logo">
                <img src="{% static 'imgs/bahari-logo.webp' %}" alt="bahari">
                Bahari Irish Pub
            </a>
            <nav class="header__nav">
                <ul class="header__nav-list">
                    <li><a href="#hero" class="header__nav-link">Home</a></li>
                    <li><a href="#about-us" class="header__nav-link">About Us</a></li>
                    <li><a href="#location" class="header__nav-link">Location</a></li>
                </ul>
            </nav>
            <div class="header__hamburger">
                <img src="{% static "imgs/icon-hamburger.svg" %}" alt="hamburger">
            </div>
            <nav class="header__sidebar header__sidebar--hidden">
                <ul class="header__sidebar-list">
                    <li><a href="#hero" class="header__nav-link">Home</a></li>
                    <li><a href="#about-us" class="header__nav-link">About Us</a></li>
                    <li><a href="#location" class="header__nav-link">Location</a></li>
                </ul>
            </nav>
        </div>
    </header>
    {% endblock %}

    <main class="main-content">
        {% block content %}{% endblock %}
    </main>

    {% block footer %}
    <footer class="footer">
        <div class="footer__container container">
            <nav class="footer__nav">
                 <ul class="footer__nav-list">
                    <li><a href="#hero" class="footer__nav-link">Home</a></li>
                    <li><a href="#about-us" class="footer__nav-link">About Us</a></li>    
                    <li><a href="#location" class="footer__nav-link">Location</a></li>
                </ul>
            </nav>
            <div class="footer__socials">
                <a href="#" target="_blank" rel="noopener noreferrer" class="footer__social-link">
                    <img src="{% static "imgs/logo-twitter.svg" %}" alt="twitter">
                </a> 
                <a href="#" target="_blank" rel="noopener noreferrer" class="footer__social-link">
                    <img src="{% static "imgs/logo-facebook.svg" %}" alt="facebook">
                </a> 
                <a href="#" target="_blank" rel="noopener noreferrer" class="footer__social-link">
                    <img src="{% static "imgs/logo-instagram.svg" %}" alt="instagram">
                </a> 
            </div>
            <p class="footer__copy">&copy; {% now 'Y' %} Bahari Irish Pub, All Rights Reserved</p>
        </div>
    </footer>
    {% endblock %}
    {% block js %}{% endblock %}
    <script>
        const hamburger = document.querySelector('.header__hamburger');
        const sidebar = document.querySelector('.header__sidebar');

        hamburger?.addEventListener('click', () => {
            sidebar.classList.toggle('header__sidebar--hidden');
        });

        window.addEventListener('click', (event) => {
            if (!sidebar.classList.contains('header__sidebar--hidden') && !sidebar.contains(event.target) && !hamburger.contains(event.target)) {
                sidebar.classList.add('header__sidebar--hidden');
            }

            if (sidebar.contains(event.target) && event.target.closest('.header__nav-link')) {
                sidebar.classList.add('header__sidebar--hidden');
            }
        });
    </script>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<section class="hero" id="hero">
    <div class="hero__image-container">
        {# Gambar Placeholder untuk Hero #}
        <img src="{% static 'imgs/placeholder-1.jpg' %}" alt="Interior Bahari Irish Pub" class="hero__image">
        <div class="hero__overlay"></div>
    </div>
    <div class="hero__content container">
        <h3 class="hero__subtitle">Welcome to</h3>
        <h1 class="hero__title">Bahari Irish Pub</h1>
        <p class="hero__text">
            A cozy, modern pub inspired by the warmth and hospitality of Ireland. Our menu features elevated Irish classics
            and a thoughtful selection of spirits, craft beers, and cocktails.
        </p>
        <a href="{% url "website:menu" %}" class="button button--primary hero__button">View Menu</a>
    </div>
</section>

<section class="events section-padding">
    <div class="events__container container">
        <h2 class="events__title">Upcoming Events</h2>
        <div class="events__grid">
            {% for event in events %}
            <div class="card">
                <img src="{% if event.photo %}{{ event.photo.url }}{% endif %}" alt="Trad Sessions" class="card__image">
                <div class="card__content">
                    <h3 class="card__title">{{ event.name }}s</h3>
                    <p class="card__text">{{ event.start_date }}</p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<section class="event-gallery section-padding">
    <div class="event-gallery__container">
        <h3 class="event-gallery__title">Post-Event Gallery</h3>
        <div class="event-gallery__content hide-scrollbar">
        {% for _ in '1234567891' %}
            <div class="event-gallery__card">
                <img src="{% static "imgs/event-gallery-placeholder.webp" %}" alt="" class="event-gallery__img">
            </div>
        {% endfor %}
        </div>
    </div>
</section>
<section class="events section-padding">
    <div class="events__container container">
        <h2 class="events__title">Live Music</h2>
        <div class="events__grid">
            {% for live in live_musics %}
            <div class="card">
                <img src="{% if live.photo %}{{ live.photo.url }}{% endif %}" alt="Trad Sessions" class="card__image">
                <div class="card__content">
                    <h3 class="card__title">{{ live.name }}</h3>
                    <p class="card__text">{{ live.schedule }}</p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<section class="passage section-padding" id="about-us">
    <div class="passage__container">
        <h2 class="passage__title">What We Are</h2>
        <p class="passage__content">
            Bahari is a modern interpretation of a traditional Irish pub. Our name means "ocean" in Irish, and we aim to bring the spirit of the sea to our landlocked location. Our space is designed with relaxed elegance, and our menu features fresh takes on classic Irish and British cuisine.
        </p>
        <p class="passage__content">
            Bahari was founded in 2023 by a group of friends who wanted to create a place where people could gather and enjoy good food and drinks. We opened our first location in the heart of downtown, and it quickly became a popular spot for locals and visitors alike. Over the years, we've expanded to other cities, but our commitment to quality and community has remained the same.
        </p>
    </div>
</section>
<section class="team">
    <div class="team__container">
        <h3 class="team__title">Our Team</h3>
        <div class="team__content">
            <div class="team__card">
                <img src="{% static "imgs/male-placeholder.svg" %}" alt="" class="team__img">
                <div class="team__identity">
                    <h5 class="team__name">Radit Marchel</h5>
                    <p class="team__role">Executive Chief</p>
                </div>
            </div>
            <div class="team__card">
                <img src="{% static "imgs/male-placeholder.svg" %}" alt="" class="team__img">
                <div class="team__identity">
                    <h5 class="team__name">Matheus Marchel</h5>
                    <p class="team__role">Executive Chief</p>
                </div>
            </div>
            <div class="team__card">
                <img src="{% static "imgs/male-placeholder.svg" %}" alt="" class="team__img">
                <div class="team__identity">
                    <h5 class="team__name">Joni Prasetyo</h5>
                    <p class="team__role">Executive Chief</p>
                </div>
            </div>
            <div class="team__card">
                <img src="{% static "imgs/female-placeholder.svg" %}" alt="" class="team__img">
                <div class="team__identity">
                    <h5 class="team__name">Desi Tampubolon</h5>
                    <p class="team__role">Executive Manager</p>
                </div>
            </div>
            <div class="team__card">
                <img src="{% static "imgs/male-placeholder.svg" %}" alt="" class="team__img">
                <div class="team__identity">
                    <h5 class="team__name">Johannes Regar</h5>
                    <p class="team__role">Creative Manager</p>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="location section-padding" id="location">
    <div class="location__container">
        <h2 class="location__title">Our Location</h2>
        <div class="location__content">
            <div class="location__map">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6011.088715915636!2d112.62587495250054!3d-7.981234354096248!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dd62905176d81eb%3A0xce6907292bcadb0c!2sBahari%20Irish%20Pub!5e0!3m2!1sen!2sid!4v1745085522501!5m2!1sen!2sid" width="100%" height="100%" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
            <div class="location__address">
                <h2 class="location__address-title">Our Location</h2>
                <p class="location__address-text">Bahari Irish Pub is located at:</p>
                <p class="location__address-text"><strong>Kawi Street No.8A, Kauman, Klojen, Malang City, East Java 65119</strong></p>
                <p class="location__address-text">We are open every day from <strong>4 PM</strong> to <strong>2 AM</strong>.</p>
                <br>
                <p class="location__address-text">bahariirishpub@gmail.com</p>
                <p class="location__address-text">Telp. +62 811 11223344</p>
            </div>
        </div>
    </div>
</section>

<div class="photo-popup photo-popup--hidden">
    <div class="photo-popup__container">
        <img src="" alt="" class="photo-popup__img">
        <button class="photo-popup__close-btn">
            <img src="{% static 'imgs/icon-close.svg' %}" alt="Close" class="photo-popup__close-icon">
        </button>
    </div>
</div>
{% endblock %}

{% block js %}
<script>
    const photoPopup = document.querySelector('.photo-popup');
    const photoPopupImg = document.querySelector('.photo-popup__img');
    const photoPopupCloseBtn = document.querySelector('.photo-popup__close-btn');
    const body = document.querySelector('body');

    document.querySelectorAll('.event-gallery__img').forEach(img => {
        img.addEventListener('click', () => {
            photoPopup.classList.remove('photo-popup--hidden');
            photoPopupImg.src = img.src;

            body.classList.toggle('no-scroll');
        });
    });

    photoPopupCloseBtn.addEventListener('click', () => {
        photoPopup.classList.add('photo-popup--hidden');
        body.classList.remove('no-scroll');
    });

    window.addEventListener('click', (event) => {
        if (event.target === photoPopup) {
            photoPopup.classList.add('photo-popup--hidden');
            body.classList.remove('no-scroll');
        }
    });
</script>
{% endblock %}

templates/menu.html
{% extends "base.html" %}
{% load static %}

{% block header %}
    <header class="header">
        <div class="header__container container">
            <a href="{% url 'website:index' %}" class="header__logo">Bahari Irish Pub</a>
            <nav class="header__nav">
                <ul class="header__nav-list">
                    <li><a href="{% url "website:index" %}#hero" class="header__nav-link">Home</a></li>
                    <li><a href="{% url "website:index" %}#about-us" class="header__nav-link">About Us</a></li>
                    <li><a href="{% url "website:index" %}#location" class="header__nav-link">Location</a></li>
                </ul>
            </nav>
            <div class="header__hamburger">
                <img src="{% static "imgs/icon-hamburger.svg" %}" alt="hamburger">
            </div>
            <nav class="header__sidebar header__sidebar--hidden">
                <ul class="header__sidebar-list">
                    <li><a href="{% url "website:index" %}#hero" class="header__nav-link">Home</a></li>
                    <li><a href="{% url "website:index" %}#about-us" class="header__nav-link">About Us</a></li>
                    <li><a href="{% url "website:index" %}#location" class="header__nav-link">Location</a></li>
                </ul>
            </nav>
        </div>
    </header>
    {% endblock %}

{% block content %}
<section class="menu">
    <div class="menu__container">
        <button class="button button--primary" id="category-trigger">Search Categories</button>
        <div class="menu__categories menu__categories--hidden">
            <div class="menu__categories-list">
                <a href="/menu?category=appetizers" class="menu__category {% if request.GET.category == "appetizers" %}active{% endif %}">
                    Appetizers
                </a>
                <a href="/menu?category=beers" class="menu__category {% if request.GET.category == "beers" %}active{% endif %}">
                    Beers
                </a>
                <a href="/menu?category=coffee" class="menu__category {% if request.GET.category == "coffee" %}active{% endif %}">
                    Coffee
                </a>
                <a href="/menu?category=main_courses" class="menu__category {% if request.GET.category == "main_courses" %}active{% endif %}">
                    Main Courses
                </a>
                <a href="/menu?category=side_dishes" class="menu__category {% if request.GET.category == "side_dishes" %}active{% endif %}">
                    Side Dishes
                </a>
            </div>
        </div>
        <div class="menu__products">
            <div class="menu__product">
                <div class="menu__product-img">
                    <img src="{% static "imgs/product-placeholder.webp" %}" alt="product">
                </div>
                <div class="menu__product-content">
                    <h5 class="menu__product-title">Irish Specialties</h5>
                    <p class="menu__product-description">
                        Our Irish specialties are a must-try for anyone wanting to experience the true flavors of Ireland.
                    </p>
                </div>
            </div>
            <div class="menu__product">
                <div class="menu__product-img">
                    <img src="{% static "imgs/product-placeholder.webp" %}" alt="product">
                </div>
                <div class="menu__product-content">
                    <h5 class="menu__product-title">Irish Specialties</h5>
                    <p class="menu__product-description">
                        Our Irish specialties are a must-try for anyone wanting to experience the true flavors of Ireland.
                    </p>
                </div>
            </div>
            <div class="menu__product">
                <div class="menu__product-img">
                    <img src="{% static "imgs/product-placeholder.webp" %}" alt="product">
                </div>
                <div class="menu__product-content">
                    <h5 class="menu__product-title">Irish Specialties</h5>
                    <p class="menu__product-description">
                        Our Irish specialties are a must-try for anyone wanting to experience the true flavors of Ireland.
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block js %}
<script>
    const categoryTrigger = document.getElementById('category-trigger');
    const categories = document.querySelector('.menu__categories');
    const body = document.querySelector('body');

    categoryTrigger.addEventListener('click', function() {
        categories.classList.toggle('menu__categories--hidden');
        body.classList.toggle('no-scroll');
    });

    window.addEventListener('click', function(event) {
        if (!categories.classList.contains('menu__categories--hidden') && !categories.contains(event.target) && !categoryTrigger.contains(event.target)) {
            categories.classList.add('menu__categories--hidden');
            body.classList.remove('no-scroll');
        }
    });
</script>
{% endblock %}